services:
    gnc_todo_app:
      image: gnc_todo_app
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - gnc_todo_database
      environment:
        DATABASE_URL: postgres://9uZYJ9wswo:qxeACNpGT4Dm6PcwkzksO9aJ@SharedPostgreSQL01A.back4app.com:5433/542c465ca42143dd9b60f8cba2267313

volumes:
  pgdata: